### ISSUE TITLE
I am getting this error - The 'files' list in config file 'tsconfig.json' is empty.

### ISSUE THREAD

**Issue by prateekshaweb** [lynnxio/frontee-boilerplate#1]
I am getting this error - The 'files' list in config file 'tsconfig.json' is empty.

npm run prod

> frontee-boilerplate@1.0.3 prod
> npm run production

> frontee-boilerplate@1.0.3 production
> mix --production

✖ Mix
  Compiled with some errors in 1.24s

ERROR in ./resources/ts/app.ts 
[tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.

ERROR in ./resources/ts/app.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (/mnt/sda1/webdesign/statamic/mysite/node_modules/ts-loader/dist/index.js:17:18)

webpack compiled with 2 errors

**Comment by zunnurs01** [comment]
Based on error message, I assume the tsconfig is missing from the starter kit. https://github.com/lynnxio/frontee-boilerplate/commit/94791d8ff187efc528b6937172d964024893bc51 I've push the possible fix.
